# Generated by Django 4.0.4 on 2022-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldFertility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('fertility', models.FloatField(blank=True, null=True)),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'world_fertility',
                'managed': False,
            },
        ),
    ]
